
services: 
  app-laravel-v1:
    container_name: app-laravel-v1
    build:
      context: .
      dockerfile: ../docker_config/web/Dockerfile
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage # Ensure storage is persisted
    ports:
      - 9000:80


  mysql-db:
    container_name: mysql-db  
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_laravel_v1
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin 
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
