
services: 
  app-laravel-v1:
    container_name: app-laravel-v1
    build:
      context: '.'
      args:
        uid: ${UID}
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000    
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80

  mysql-db:
    container_name: mysql-db  
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_laravel_v1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3307
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    container_name: phpmyadmin 
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
